export const interests = [
  [
    'karate',
    'bob-sledding',
    'movies',
    'snooker',
    'true-crime podcasts',
    'cars',
    'indie music',
    'coffee',
    'mixed martial arts',
    'hockey',
    'game shows',
    'alternative comedy',
    'camping',
  ],
  [
    'swimming',
    'dining in',
    'woodworking',
    'arts and crafts',
    'stamp collecting',
    'browsing stores',
    'exercising',
    'food tasting',
    'sports',
    'hiking',
    'reading',
    'movies',
    'camping',
  ],
  [
    'bird watching',
    'canooing',
    'darts',
    'jumping rope',
    'antiques',
    'shooting',
    'fencing',
    'arobics',
    'bouldering',
    'archery',
    'museums',
    'shopping',
    'gardening',
  ],
  [
    'history',
    'wrestling',
    'science',
    'basketball',
    'stand-up comedy',
    'tech',
    'teaching',
    'civics and government',
    'languages',
    'sculptures',
    'skiing',
    'whale watching',
    'podcasts',
  ],
  [
    'surfing',
    'trees',
    'tennis',
    'horror',
    'brazilian jiu-jitsu',
    'drums',
    'classical music',
    'judo',
    'golf',
    'deserts',
    'improv comedy',
    'alternative music',
    'hip-hop',
  ],
];
