export const Paths = {
  signup: 'SignUp',
  signin: 'SignIn',
  firstphoto: 'FirstPhoto',
  interests: 'Interests',
  start: 'Start',
  userprofile: 'Me',
  edituser: 'EditUser',
  posts: 'Search',
  postsNavigation: 'Post main',
  onboardingNavigation: 'OnboardingNavigation',
  newPostNavigation: 'New Post',
  userNavigation: 'UserNavigation',
  preview: 'Preview',
  adddestination: 'AddDestination',
  newpost: 'NewPost',
  favoriteposts: 'Saved',
  notifications: 'Notifications',
};
